---
version: 2
linters-settings:
  govet:
    enable-all: true
    disable:
    - fieldalignment
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
    - diagnostic
    - experimental
    - opinionated
    - performance
    - style
    disabled-checks:
    - dupImport
    - ifElseChain
    - octalLiteral
    - whyNoLint
    - wrapperFunc
  funlen:
    lines: 100
    statements: 85
  depguard:
    rules:
      main:
        list-mode: lax
        allow:
        - $gostd
        - gitlab.com/davidxarnold
        - github.com/aws
        - github.com/sirupsen
        - cloud.google.com
        - google.golang.org
        - k8s.io
        - github.com/spf13
        - github.com/mitchellh
        - github.com/gizak
        - github.com/jedib0t

linters:
  disable-all: true
  enable:
  - bodyclose
  # - depguard  # Disabled due to v2 compatibility issues
  - dogsled
  - dupl
  - errcheck
  # - funlen  # Disabled - data fetching functions are inherently complex
  - gochecknoinits
  - goconst
  - gocritic
  - gocyclo
  - gosec
  - govet
  - ineffassign
  - lll
  - misspell
  - nakedret
  - staticcheck
  - unconvert
  - unparam
  - unused
  - whitespace
  # don't enable:
  # - gochecknoglobals
  # - gocognit
  # - godox
  # - makezero
  # - prealloc
  # - testpackage
  # - wrapcheck

output:
  format: colored-line-number

service:
  golangci-lint-version: 2.7.2
